### ISSUE TITLE
Headers not printing while exporting/printing to pdf

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#13]
Headers don't print out while exporting to pdf. Is there an issue or am i missing something?

![image](https://github.com/ronkok/Hurmet/assets/17706904/1557b098-ba67-40f7-ae75-f51bce008137)
I'm supposed to get headers printed out. Isn't it?

See exported pdf below. 

![image](https://github.com/ronkok/Hurmet/assets/17706904/b3559d3a-b5ae-494d-8493-f8ff0f390bc3)

I'm using edge browser. It doesn't work in Firefox too.

**Comment by ronkok** [comment]
Don't use Ctrl-P to print. Instead invoke the Hurmet menu choice **File | Print …**.

Sorry about that, but browser native print headers are bad. I had to write my own pagination.

I'll work on re-directing Ctrl-P to the Hurmet print command. It should be working tomorrow.

**Comment by ronkok** [comment]
Also, the print header does not appear on the first page. That enables you to make the first page a cover sheet. The print header appears on every page after the first one.

**Comment by swopnil123** [comment]
> Also, the print header does not appear on the first page. That enables you to make the first page a cover sheet. The print header appears on every page after the first one.

Awesome! It works. This is a great app/tool for structural engineers. Thank you
