### ISSUE TITLE
Dataframe feature requests

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#15]
This feature to add items in data frames would be great. It would make calcs look more presentable.

![image](https://github.com/ronkok/Hurmet/assets/17706904/b93f9268-26cd-4af2-a02f-5d1c473b6cf0)

**Comment by ronkok** [comment]
Hurmet can now prepend a vertical vector to a dataframe. You'll get the updated version of Hurmet the next time you open it (after being away for at least 4 hours).
