### ISSUE TITLE
Unit aware inside matrix

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#16]
Hurmet fails to perform unit aware calcs inside a matrix

![image](https://github.com/ronkok/Hurmet/assets/17706904/cfbaf00f-18d7-4cbf-b713-d4d81901ea7e)

![image](https://github.com/ronkok/Hurmet/assets/17706904/1054aacd-688b-4b2a-bdd2-fa9a2e10e353)

**Comment by swopnil123** [comment]
Doesn't work if you perform unit aware calcs outside and create a vector from it? Can it be made to work? This feature is handy at times.

![image](https://github.com/ronkok/Hurmet/assets/17706904/bff94a92-6162-486a-940d-9ad17a635a68)

**Comment by ronkok** [comment]
You can write elements that call in variables. But that must be done without units. Then you can assign a unit to the resulting matrix, like this:

`weight = [w_1stfloor, w_2ndfloor] = ? lbf `

**Comment by swopnil123** [comment]
Thanks! That makes sense. Just a little bit caution needed inside matrices and vectors.
I'll close this once you, write proper information/warning message.

**Comment by swopnil123** [comment]
Thanks  warnings start to appear
