### ISSUE TITLE
Feature request Override matrix element

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#18]
Is it possible to override a predefined matrix/vector element? It can be very handy at times.

![image](https://github.com/ronkok/Hurmet/assets/17706904/39af5eda-4266-4336-a361-615dbbd5a5af)

**Comment by ronkok** [comment]
Matrices are immutable. You cannot modify an element of an existing matrix. You can, however, reassign the variable with a new matrix, like this: 
![image](https://github.com/ronkok/Hurmet/assets/16403058/2dacba36-f953-4250-b304-0d220c2da47a)
