### ISSUE TITLE
Previously save file won't open in hurmet

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#19]
I have a an issue with a file. It contains lot of pictures, images for referencing calcs. It was working fine and I made changes and saved it.  But it won't open. Any idea?

I also noticed that there the page printer behaves in an unexpected way when we put images, files.

**Comment by ronkok** [comment]
Pictures can get very large. I've seen one Hurmet file balloon up to 68 Meg because of the embedded images. It opened, but it was sluggish.

If you want to email your file to ronkok55 at outlook.com, I can take a look at it.

**Comment by swopnil123** [comment]
I see it's best not to use embedded images too much. Perhaps upto 3-4 per file is fine. Anything more than that makes the file sluggish and prints behave in an expected way. 

Best practice is to use urls (upload images somewhere in Google drive or drop box etc) This way file will be very smooth.

**Comment by swopnil123** [comment]
> Pictures can get very large. I've seen one Hurmet file balloon up to 68 Meg because of the embedded images. It opened, but it was sluggish.
> 
> If you want to email your file to ronkok55 at outlook.com, I can take a look at it.

Thank you but won't be able to do that.
