### ISSUE TITLE
Lines not appearing in PM interaction 

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#21]
Curve not appearing in the PM interaction chart. I think it used to work perfectly fine a couple of days ago. 

![image](https://github.com/ronkok/Hurmet/assets/17706904/7fb334d6-3ab0-4503-a7b2-ca71f99b1355)

**Comment by ronkok** [comment]
I am experiencing the same problem. I'll have a fix in place tomorrow.
