### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by JafarAkhondali** [ronkok/Hurmet#23]
We are a group of researchers from Leiden University, and we conduct research on vulnerabilities in open-source software. We have discovered and verified a high-severity vulnerability in your project(ronkok/Hurmet). Explaining the vulnerability further in this issue could allow malicious users to access details, so we recommend [enabling private vulnerability reporting on GitHub](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to discuss this matter confidentially.
        After you have enabled this feature, please add a comment to this issue so we can continue our discussion. If you have any questions, feel free to leave a reply here or send an email to: j.akhoundali [at] liacs.leidenuniv.nl

**Comment by ronkok** [comment]
I've enabled private vulnerability reporting. It's your move.

**Comment by ronkok** [comment]
False alarm. I've removed the file in question, just to eliminate tedious follow up discussions.
