### ISSUE TITLE
Issues with dataframe 

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#24]
There seems to be some sort of issue with dataframe. Its not working correctly right now

![image](https://github.com/ronkok/Hurmet/assets/17706904/1e2ceb9d-afae-4319-b668-d17e54619473)

**Comment by ronkok** [comment]
It's fixed now. You will get a corrected version of Hurmet the next time you navigate there after being away for four hours.

Thank you for bringing this to my attention.
