### ISSUE TITLE
UDF with vectors

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#26]
This may not be an appropriate title for this. But can you answer me why we cannot return values from UDF if we put vectors as an argument?

![image](https://github.com/ronkok/Hurmet/assets/17706904/eac7c03c-58d3-4920-9c32-3ca6899d8211)

**Comment by ronkok** [comment]
I'll look into it.

Please include the text of your example, so I don't have to retype what I see in an image.

**Comment by swopnil123** [comment]
> I'll look into it.
> 
> Please include the text of your example, so I don't have to retype what I see in an image.

I'm uploading the file here. You can take a look. Thank you!
[HurmetFile (1).md](https://github.com/user-attachments/files/16054968/HurmetFile.1.md)

**Comment by ronkok** [comment]
Say that a function contains a condition:

```
if condition
    V = scalar × vector
else
    V = scalar
end
```

Hurmet will either multiply the scalar times all of the vector or none of it. Hurmet conditions are not disguised `for` loops.

If you want a function to apply a condition to each element in a vector, you'll need to write your own `for` loop. For this example, you'll want a function something like:

```
function Ch2(T, T_a, T_c, T_d, α)
    C = []
    for el in T
        if el ≤ T_a
            C = C & (1 + (α - 1) × el / T_a)
        elseif T_a ≤ el and el ≤ T_c
            C = C & α
        elseif T_c ≤ el and el ≤ T_d
            C = C & α × T_c/el
        elseif  el ≥ T_d
            C = C & (α × T_c × T_d) / el²
        end
    end
    return C
end
```

I've just fixed a bug in Hurmet's `for` loop. You'll get the updated code the next time you navigate to Hurmet.org after being away for four hours.

**Comment by swopnil123** [comment]
Thanks! a lot. This helps. 

I'm closing this. I'll try to plot these for different scenario and if anything arises then I'll report it as a separate issue.
