### ISSUE TITLE
Issues with dataframe

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#28]
There seems to be an issue with the dataframe. Dataframe function fails to work if the UDF is suppressed using !. 

![image](https://github.com/ronkok/Hurmet/assets/17706904/79d0629c-8720-4978-ad64-bdc08b7dcdc0)

If ? is used then works

![image](https://github.com/ronkok/Hurmet/assets/17706904/10ce41ff-b60b-4119-bec8-7b7dcb874f7b)

This is the error. 
![image](https://github.com/ronkok/Hurmet/assets/17706904/85dc989a-b056-4b5c-8da3-5974f4de1294)

**Comment by ronkok** [comment]
Fixed now.

**Comment by swopnil123** [comment]
Its weird I'm getting dataframe header as PS_a. Shouldn't it be S_a?

![image](https://github.com/ronkok/Hurmet/assets/17706904/532358c8-56de-46dd-a2a0-2d421aeb68ff)

**Comment by ronkok** [comment]
Fixed now.

**Comment by swopnil123** [comment]
Awesome! Thank you.
