### ISSUE TITLE
Potential bug in Steel Member Strength module

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#30]
Can you explain me what did I do wrong here? Its giving unexpected weird results. 

![image](https://github.com/user-attachments/assets/e3de0aaa-f740-451a-9b33-fe40e77f57bf)

¢` format = "h2" `

¢` mod =
import("https://gist.githubusercontent.com/ronkok/f4d93a4921ebd24c9a40578831d926b7/raw/steelStrengthPerAISC360-16.txt")=! `, Import module

¢` AISCWFTable=
fetch("https://gist.githubusercontent.com/ronkok/d2ae5b3c74889e71c7bb8422b6017067/raw/AISC-v15-wideFlanges.tsv")=! `, Import AISC Wide Flange Table¢`  `

¢` kLx = 10ft `, Unbraced length about major axis

¢` kLy = 15ft `, Unbraced length about minor axis

¢` F_y = 50ksi `, Specified Yield Strength of Steel

¢` Section = "W16X36" `, Section used for 

¢` ϕP_n = mod.Ps(AISCWTable[Section],F_y,kLx,kLy)=??kip `

¶

**Comment by swopnil123** [comment]
The problem lies here

![image](https://github.com/user-attachments/assets/daf83622-cbfe-44fc-9271-ac40c3616317)

**Comment by ronkok** [comment]
Thank you for pointing this out. I have corrected the equation.
