### ISSUE TITLE
Feature Request to use if statements inside spreadsheets

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#31]
I think the title says it all. Can you include this feature to use if statements inside spreadsheet table? This would be very useful in many cases.

**Comment by ronkok** [comment]
IF Expressions already work inside spreadsheets. For a test case, copy the following expression into a spreadsheet cell.

```
={0.1 if 2 > 0; 0.2 otherwise}
```

Toggle the spreadsheet to see the result (0.1). Then redo it with a different condition, say `if 2 > 3`.

**Comment by swopnil123** [comment]
Thanks! This is great. 

One more question. Can we extract column header or row header from spreadsheets? For instance, we could extract full weight column here in this example.

![image](https://github.com/user-attachments/assets/066b9a83-4540-45d5-b438-221643784229)

**Comment by ronkok** [comment]
At this time, row headers and column headers cannot be extracted as in your example. I'll put it on the To Do list and I'll get to it eventually. Probably not right away. I'm a little busy right now.

**Comment by ronkok** [comment]
Since the original topic has been resolved, I am closing this issue. If you want more visibility for your row header request, open another issue.
