### ISSUE TITLE
String Interpolation inside dataframes not working

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#32]
There seems to be a bug. I'm doing exactly what is shown in the documentation manual. 

![image](https://github.com/user-attachments/assets/fe835974-e178-4b1a-8ed6-5b7babda544e)

![image](https://github.com/user-attachments/assets/2c6b1563-2f94-457f-9867-7289dd7d7fa5)

**Comment by ronkok** [comment]
Yep, that was a bug. Fixed now. You'll get the updated version the next time you navigate to Hurmet.org after a 4-hour absence.

Note that I have also revised the documentation. The example of string interpolation now reads:
```
w = ``dead	live	snow
${w_dead}	30	40`` 'lbf/ft' = %% lbf/ft
```

**Comment by ronkok** [comment]
I appreciate your attention to detail and how you identify issues. In future communications, it would be very helpful if you would write your example in text that I can copy and paste. When you paste in screenshots, I am forced to retype your work.

**Comment by swopnil123** [comment]
Thanks Ron. I will keep that in mind.
