### ISSUE TITLE
Retrieving Column Headers and Row Headers from Hurmet Spreadsheets.

### ISSUE THREAD

**Issue by swopnil123** [ronkok/Hurmet#33]
Can you add a feature that allows to extract column headers and row headers from a Hurmet Spreadsheet?

¢` format ="h2" `

¢` k = 1 `

¢` V_base = 500kips `

: Table1 Seismic Force Distribution
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| Floor  | Weight\  | Height\ | w × h^k^ | C~vs~     | Force\       | Shear\ | Overturning\   |
|        | kips     | ft      |          |           | kips         | kips   | kip·ft         |
+========+:========:+:=======:+:========:+:=========:+:============:+:======:+:==============:+
| roof   | 950      | 70      | =B1×C1^k | =D1/D_end | ==E1× V_base | =F1    | 0              |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| fifth  | 1,250    | 56      | "        | "         | "            | =G1+F2 | =H1+G1×(C1-C2) |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| fourth | "        | 42      | "        | "         | "            | "      | "              |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| third  | "        | 28      | "        | "         | "            | "      | "              |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| second | "        | 14      | "        | "         | "            | "      | "              |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
| total  | =sum(up) | 0       | =sum(up) |           | =sum(up)     | =F_end | "              |
+--------+----------+---------+----------+-----------+--------------+--------+----------------+
{#Table1 ."four-rules spreadsheet" colWidths="70 71 62 73 88 74 76 null"}

¶

¢` Table1.Weight=??kips `

¢` Table1.Floor=? `

¶

**Comment by ronkok** [comment]
This is a reasonable request. I'll start to give it some thought.

**Comment by ronkok** [comment]
Thank you for providing an example in text format. It would be even better if the entire block of text was written as a code block between triple back ticks, as in:

````
```
Write a code block between triple backticks.

¢` w = 0.2 kips/ft `

¢` L = 12 ft `

¢` M = (w L²) / 8 = ?? kip·ft `
```
````

**Comment by ronkok** [comment]
I've fixed a bug and now the first column can be called into a column vector.

What is the use case for calling the top row?

**Comment by swopnil123** [comment]
Thank you! Not much of a use of top row. I just asked you randomly. 
I'm closing this.
