### ISSUE TITLE
False @test statements throwing ParseError when assert="String" used

### ISSUE THREAD

**Issue by MatthewDSloss** [ronkok/Hurmet#41]
I am looking to add descriptive OK/NG to a document but when I present the below, it is throwing errors.

```
assert = "message"
@@test [FALSE statement]
```

Here's the input in a document.
![image](https://github.com/user-attachments/assets/52609e1a-f33b-420f-ae98-3c8b66a9fe9e)
When it is run, the below appears.
![image](https://github.com/user-attachments/assets/a5a2f596-54be-49fb-a11f-a98dc988b82a)

Curiously, the text is present in the draft mode, it just doesn't render properly in document view.
![image](https://github.com/user-attachments/assets/e3dcb69d-dac3-4c27-b451-619577319ff4)

**Comment by ronkok** [comment]
Yep, that was a bug. It's fixed now. You'll get the updated version the next time you visit the site after being away for at least 4 hours.

Thank you for bringing this to my attention.

**Comment by MatthewDSloss** [comment]
Thank you for the fix. It seems to have introduced a new bug, unfortunately. When copying and pasting test statements, it defaults to the below formatting:
![image](https://github.com/user-attachments/assets/99f1ec7a-a68a-47d2-845a-7136043754d4)

When parsed, it displays as below:
![image](https://github.com/user-attachments/assets/60d023c4-a4a1-4456-b63a-751d82c2d11d)

This is fixed by introducing a space between the <= as seen below:
![image](https://github.com/user-attachments/assets/77e13c33-02bb-41a4-aa33-adcba2a790f2)

**Comment by ronkok** [comment]
Good catch. I just pushed a patch that fixes this problem. You'll get it the next time you open Hurmet after being away for 4 hours.

Thanks for bringing this to my attention.
