### ISSUE TITLE
Unexpected rounding behavior using the "h" formatting

### ISSUE THREAD

**Issue by MatthewDSloss** [ronkok/Hurmet#42]
I've encountered an unintuitive rounding behavior when using the formatting tag `format = "h#"`

Below is the value when using h5
![image](https://github.com/user-attachments/assets/5aacfb65-3b54-4ab2-ac31-8583f6b0502d)

Now if I reduce the value of my formatting string to h3
![image](https://github.com/user-attachments/assets/2c3a15e6-a773-4e38-9d2b-7185937ea84f)

It is not clear how P_bmup is getting rounded to -154 instead of -155 or the expected -156

**Comment by ronkok** [comment]
This is a serious error. Thank you so much for bringing it to my attention.  I'm booked up today, but I will fix this tomorrow.

**Comment by ronkok** [comment]
I found some time and fixed it. You should be good to go.
