### ISSUE TITLE
Compound units not functional, returning "Error. Variable '[UNIT]' not found" 

### ISSUE THREAD

**Issue by MatthewDSloss** [ronkok/Hurmet#44]
When creating compound units (such as kip*ft for a moment), the unit solver appears to try and parse the unit as a variable rather than combining with the other units. I believe this to be a regression from previous versions

![image](https://github.com/user-attachments/assets/5c95f95e-7619-44d2-84b6-b9a7305315e1)
![image](https://github.com/user-attachments/assets/05a624b9-76b0-4e8b-884f-48eb291ad220)

This is also seen when using the examples in the documentation page
![image](https://github.com/user-attachments/assets/364ff00a-54b6-4329-b18a-4a37b0a178c5)

**Comment by MatthewDSloss** [comment]
![image](https://github.com/user-attachments/assets/e227cf07-2042-4bd9-969e-7a317aa5bf85)
Oddly this is not an issue when simply assigning a variable with a compound unit and then using it in an equation later.

**Comment by ronkok** [comment]
Fixed now. Thank you for the heads up.

You'll get the updated version the next time you visit Hurmet.org after being away for 4 hours.
