### ISSUE TITLE
Rounding off error while displaying decimal values.

### ISSUE THREAD

**Issue by subhamsp7** [ronkok/Hurmet#45]
Numbers after decimal place is showing .100 for .999 values.

![Screenshot 2024-12-23 100229](https://github.com/user-attachments/assets/071e3875-9f44-44f2-9b1c-b4f2d00eb3e0)

**Comment by ronkok** [comment]
Yup, that's a bug. I've found where the error occurs. I'll fix it tomorrow.

**Comment by ronkok** [comment]
Fixed now. You'll get the updated version the next time you navigate to Hurmet.org after being away for 4 hours.
